# Generated by Django 3.2.19 on 2023-07-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='dated_created',
            new_name='date_created',
        ),
    ]
