# Generated by Django 3.2.19 on 2023-08-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
